### ISSUE TITLE
Add documentation for CSS custom states

### ISSUE THREAD

**Issue by KonnorRogers** [shoelace-style/webawesome#168] opened 2024-09-03 17:59 UTC
Mainly `WebAwesomeFormControl` which uses `:state(user-valid)`, `:state(user-invalid)`, `:invalid`, `:disabled`, and `:valid`

**Comment by claviska** [comment] 2024-11-06 20:50
Duplicate of #129. Added your comment there.

**Closed as completed by claviska** 2024-11-06 20:50 UTC
