### ISSUE TITLE
Can't expand the components section in the sidebar in Safari

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#368] opened 2024-12-19 23:26 UTC
https://github.com/user-attachments/assets/2c4594ac-be5b-417d-a8f5-9df706b2c17e

**Comment by kelseythejackson** [comment] 2024-12-20 01:05
It's happening on Chrome & Firefox too

**Comment by LeaVerou** [comment] 2024-12-20 01:18
I cannot reproduce in Safari 18.1 🤔

**Comment by LeaVerou** [comment] 2024-12-20 01:31
@KonnorRogers said this was fixed in https://github.com/shoelace-style/webawesome/commit/835326a2dbca14d981ca2aaa8abbc9da167fcf7a

**Closed as completed by LeaVerou** 2024-12-20 01:31 UTC
Labels: bug, high priority
